version: '3.1'
services:

  postgres_test:
    image: postgres
    ports:
      - 15432:5432
    restart: always
    environment:
      POSTGRES_USER: dbusr
      POSTGRES_PASSWORD: dbpwd
      POSTGRES_DB: testdb
    volumes:
      - ./volume/postgresql:/var/lib/postgresql/testdata