version: '3.1'
services:

  postgres_app:
    image: postgres
    ports:
      - 25432:5432
    restart: always
    environment:
      POSTGRES_USER: dbusr
      POSTGRES_PASSWORD: dbpwd
      POSTGRES_DB: appdb
    volumes:
      - ./volume/postgresql:/var/lib/postgresql/apdata

