version: '3.1'
services:

  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: jesus_usr
      POSTGRES_PASSWORD: jesus_psswd
      POSTGRES_DB: jesus_db
    volumes:
      - ./volume/postgresql:/var/lib/postgresql/data


